[build]
  base = "."
  publish = "frontend/dist"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "20"

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

# SPA redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  included_files = [
    "backend/dist/**",
    "netlify/functions/backend-dist/**"
  ]
  node_bundler = "esbuild"
  external_node_modules = [
    "express",
    "serverless-http",
    "mongoose",
    "cors",
    "helmet",
    "compression",
    "express-rate-limit",
    "express-validator",
    "jsonwebtoken",
    "bcryptjs",
    "cloudinary",
    "multer",
    "nodemailer",
    "pdfkit",
    "razorpay",
    "stripe",
    "dotenv"
  ]

[dev]
  command = "npm run dev"
  port = 3000
  publish = "frontend/dist"
