[build]
  base = "."
  publish = "frontend/dist"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "20"

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

# SPA redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  included_files = [
    "backend/dist/**"
  ]
  node_bundler = "none"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "frontend/dist"
